name: Podman CI/CD

on:
  schedule:
    - cron: '22 22 22 * *'
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  REGISTRY: quay.io
  NAMESPACE: kasra_amirsarvari
  IMAGE_NAME: ansible-molecule-fedora-34
  TAG: latest

jobs:
  build_test_push:
    name: Build test and push to Quay
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build the image
        run: sudo podman build -t ${{ env.REGISTRY }}/${{ env.NAMESPACE }}/${{ env.IMAGE_NAME }}:${{ env.TAG }} .

      - name: Get image list
        run: sudo podman images

      - name: Run the container
        run: >
          sudo podman run -d
          --name ansible-molecule
          --privileged
          --volume /sys/fs/cgroup:/sys/fs/cgroup:ro
          ${{ env.REGISTRY }}/${{ env.NAMESPACE }}/${{ env.IMAGE_NAME }}:${{ env.TAG }}
          /usr/sbin/init

      - name: Get container list
        run: sudo podman ps -a

      - name: Get logs on created container
        run: sudo podman logs -t -n ansible-molecule

      - name: Verify the container
        run: sudo podman exec --tty ansible-molecule env

      - name: Login to registry
        run: sudo podman login --username ${{ secrets.QUAY_USERNAME }} --password ${{ secrets.QUAY_PASSWORD }} ${{ env.REGISTRY }}

      - name: Push to registry
        run: sudo podman push ${{ env.REGISTRY }}/${{ env.NAMESPACE }}/${{ env.IMAGE_NAME }}:${{ env.TAG }}
